### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [FalconLee1011/mint-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by FalconLee1011** [comment]
Thanks for discovering my zsh theme! Pleasure to be added to the plugin list!, The license has been added in 8057256!
